import type { HttpStatusCategory } from './http-status-codes.constants';

export const codesByCategoriesZh: HttpStatusCategory[] = [
  {
    category: '1xx 信息响应',
    codes: [
      {
        code: 100,
        name: '继续',
        description: '等待客户端发送请求体。',
        type: 'HTTP',
      },
      {
        code: 101,
        name: '切换协议',
        description: '服务器已同意切换协议。',
        type: 'HTTP',
      },
      {
        code: 102,
        name: '处理中',
        description: '服务器正在处理请求，但尚未有可用响应。',
        type: 'WebDav',
      },
      {
        code: 103,
        name: '早期提示',
        description: '服务器在最终 HTTP 消息之前返回一些响应头。',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '2xx 成功',
    codes: [
      {
        code: 200,
        name: '成功',
        description: '成功 HTTP 请求的标准响应。',
        type: 'HTTP',
      },
      {
        code: 201,
        name: '已创建',
        description: '请求已完成，并创建了一个新资源。',
        type: 'HTTP',
      },
      {
        code: 202,
        name: '已接受',
        description: '请求已被接受进行处理，但处理尚未完成。',
        type: 'HTTP',
      },
      {
        code: 203,
        name: '非权威信息',
        description: '请求成功，但原始请求的内容已被转换代理修改。',
        type: 'HTTP',
      },
      {
        code: 204,
        name: '无内容',
        description: '服务器成功处理了请求，但不返回任何内容。',
        type: 'HTTP',
      },
      {
        code: 205,
        name: '重置内容',
        description: '服务器指示重新初始化发送此请求的文档视图。',
        type: 'HTTP',
      },
      {
        code: 206,
        name: '部分内容',
        description: '由于客户端发送了 Range 头，服务器只返回资源的一部分。',
        type: 'HTTP',
      },
      {
        code: 207,
        name: '多状态',
        description: '后续的消息体是 XML 消息，可包含多个独立的响应码。',
        type: 'WebDav',
      },
      {
        code: 208,
        name: '已报告',
        description: 'DAV 绑定的成员已在（多状态）响应的前一部分中枚举。',
        type: 'WebDav',
      },
      {
        code: 226,
        name: '已使用 IM',
        description: '服务器已满足对资源的请求，响应是结果的表示。',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '3xx 重定向',
    codes: [
      {
        code: 300,
        name: '多种选择',
        description: '表示客户端可以跟随的资源的多个选项。',
        type: 'HTTP',
      },
      {
        code: 301,
        name: '永久移动',
        description: '此请求及所有后续请求应指向给定的 URI。',
        type: 'HTTP',
      },
      {
        code: 302,
        name: '找到',
        description: '重定向到另一个 URL。这是行业实践与标准相矛盾的例子。',
        type: 'HTTP',
      },
      {
        code: 303,
        name: '查看其他位置',
        description: '请求的响应可以在另一个 URI 下使用 GET 方法找到。',
        type: 'HTTP',
      },
      {
        code: 304,
        name: '未修改',
        description: '表示资源自请求头指定的版本以来未被修改。',
        type: 'HTTP',
      },
      {
        code: 305,
        name: '使用代理',
        description: '请求的资源只能通过代理访问，代理地址在响应中提供。',
        type: 'HTTP',
      },
      {
        code: 306,
        name: '切换代理',
        description: '不再使用。最初含义是「后续请求应使用指定的代理」。',
        type: 'HTTP',
      },
      {
        code: 307,
        name: '临时重定向',
        description: '请求应使用另一个 URI 重发；但后续请求仍应使用原始 URI。',
        type: 'HTTP',
      },
      {
        code: 308,
        name: '永久重定向',
        description: '请求及所有后续请求应使用另一个 URI 重发。',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '4xx 客户端错误',
    codes: [
      {
        code: 400,
        name: '错误请求',
        description: '由于明显的客户端错误，服务器不能或不会处理该请求。',
        type: 'HTTP',
      },
      {
        code: 401,
        name: '未授权',
        description: '类似于 403 禁止访问，但专门用于需要认证且认证失败或尚未提供的情况。',
        type: 'HTTP',
      },
      {
        code: 402,
        name: '需要付费',
        description: '保留供将来使用。最初意图是用于某种形式的数字现金或小额支付方案。',
        type: 'HTTP',
      },
      {
        code: 403,
        name: '禁止访问',
        description: '请求有效，但服务器拒绝执行操作。用户可能没有访问资源的必要权限。',
        type: 'HTTP',
      },
      {
        code: 404,
        name: '未找到',
        description: '请求的资源无法找到，但将来可能可用。',
        type: 'HTTP',
      },
      {
        code: 405,
        name: '方法不允许',
        description: '请求的资源不支持该请求方法。',
        type: 'HTTP',
      },
      {
        code: 406,
        name: '不可接受',
        description: '请求的资源只能生成根据请求中发送的 Accept 头不可接受的内容。',
        type: 'HTTP',
      },
      {
        code: 407,
        name: '需要代理认证',
        description: '客户端必须先通过代理进行身份认证。',
        type: 'HTTP',
      },
      {
        code: 408,
        name: '请求超时',
        description: '服务器等待请求超时。',
        type: 'HTTP',
      },
      {
        code: 409,
        name: '冲突',
        description: '表示请求因请求中的冲突（如编辑冲突）而无法处理。',
        type: 'HTTP',
      },
      {
        code: 410,
        name: '已消失',
        description: '表示请求的资源不再可用，且将来也不会再次可用。',
        type: 'HTTP',
      },
      {
        code: 411,
        name: '需要内容长度',
        description: '请求未指定其内容长度，而这是请求资源所必需的。',
        type: 'HTTP',
      },
      {
        code: 412,
        name: '前置条件失败',
        description: '服务器不满足请求方在请求中提出的前置条件之一。',
        type: 'HTTP',
      },
      {
        code: 413,
        name: '载荷过大',
        description: '请求大于服务器愿意或能够处理的大小。',
        type: 'HTTP',
      },
      {
        code: 414,
        name: 'URI 过长',
        description: '提供的 URI 太长，服务器无法处理。',
        type: 'HTTP',
      },
      {
        code: 415,
        name: '不支持的媒体类型',
        description: '请求实体具有服务器或资源不支持的媒体类型。',
        type: 'HTTP',
      },
      {
        code: 416,
        name: '范围无法满足',
        description: '客户端请求了文件的一部分，但服务器无法提供该部分。',
        type: 'HTTP',
      },
      {
        code: 417,
        name: '期望失败',
        description: '服务器无法满足 Expect 请求头字段的要求。',
        type: 'HTTP',
      },
      {
        code: 418,
        name: '我是茶壶',
        description: '服务器拒绝用茶壶煮咖啡的尝试。',
        type: 'HTTP',
      },
      {
        code: 421,
        name: '误导的请求',
        description: '请求被定向到无法产生响应的服务器。',
        type: 'HTTP',
      },
      {
        code: 422,
        name: '无法处理的实体',
        description: '请求格式良好，但由于语义错误而无法处理。',
        type: 'HTTP',
      },
      {
        code: 423,
        name: '已锁定',
        description: '正在访问的资源被锁定。',
        type: 'HTTP',
      },
      {
        code: 424,
        name: '依赖失败',
        description: '请求因前一个请求失败而失败。',
        type: 'HTTP',
      },
      {
        code: 425,
        name: '太早',
        description: '表示服务器不愿冒险处理可能被重放的请求。',
        type: 'HTTP',
      },
      {
        code: 426,
        name: '需要升级',
        description: '客户端应切换到不同的协议，如 TLS/1.0。',
        type: 'HTTP',
      },
      {
        code: 428,
        name: '需要前置条件',
        description: '源服务器要求请求是有条件的。',
        type: 'HTTP',
      },
      {
        code: 429,
        name: '请求过多',
        description: '用户在给定时间内发送了过多请求。',
        type: 'HTTP',
      },
      {
        code: 431,
        name: '请求头字段过大',
        description: '服务器不愿处理该请求，因为单个头字段或所有头字段总体过大。',
        type: 'HTTP',
      },
      {
        code: 451,
        name: '因法律原因不可用',
        description: '服务器运营商收到了拒绝访问某个资源或一组资源（包括请求的资源）的法律要求。',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '5xx 服务器错误',
    codes: [
      {
        code: 500,
        name: '服务器内部错误',
        description: '遇到意外情况且没有更具体的消息适用时给出的通用错误消息。',
        type: 'HTTP',
      },
      {
        code: 501,
        name: '未实现',
        description: '服务器无法识别请求方法，或缺少满足请求的能力。',
        type: 'HTTP',
      },
      {
        code: 502,
        name: '网关错误',
        description: '服务器充当网关或代理，从上游服务器收到了无效响应。',
        type: 'HTTP',
      },
      {
        code: 503,
        name: '服务不可用',
        description: '服务器当前不可用（因为过载或维护停机）。',
        type: 'HTTP',
      },
      {
        code: 504,
        name: '网关超时',
        description: '服务器充当网关或代理，未及时收到上游服务器的响应。',
        type: 'HTTP',
      },
      {
        code: 505,
        name: '不支持 HTTP 版本',
        description: '服务器不支持请求中使用的 HTTP 协议版本。',
        type: 'HTTP',
      },
      {
        code: 506,
        name: '变体协商',
        description: '请求的透明内容协商导致循环引用。',
        type: 'HTTP',
      },
      {
        code: 507,
        name: '存储不足',
        description: '服务器无法存储完成请求所需的表示。',
        type: 'HTTP',
      },
      {
        code: 508,
        name: '检测到循环',
        description: '服务器在处理请求时检测到无限循环。',
        type: 'HTTP',
      },
      {
        code: 510,
        name: '未扩展',
        description: '服务器需要进一步的扩展才能满足请求。',
        type: 'HTTP',
      },
      {
        code: 511,
        name: '需要网络认证',
        description: '客户端需要进行身份认证才能获得网络访问权限。',
        type: 'HTTP',
      },
    ],
  },
];
